Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-02, with the labels that each got.

#670 Accessibility (Skip to Content, Headings, Lang Attr), Page Layout Changes
  app/Providers/ViewComposerServiceProvider.php
  public/css/app.css
  public/mix-manifest.json
  resources/assets/sass/app.scss
  resources/lang/en/common/goc.php
  resources/lang/en/common/hero.php
  resources/lang/fr/common/goc.php
  resources/lang/fr/common/hero.php
  resources/views/applicant/application_index.html.twig
  resources/views/applicant/application_post_01.html.twig
  resources/views/applicant/application_post_02.html.twig
  resources/views/applicant/application_post_03.html.twig
  resources/views/applicant/application_post_04.html.twig
  resources/views/applicant/application_post_05.html.twig
  resources/views/applicant/application_post_complete.html.twig
  resources/views/applicant/application_preview.html.twig
  resources/views/applicant/home.html.twig
  resources/views/applicant/home/how.html.twig
  resources/views/applicant/home/team.html.twig
  resources/views/applicant/job_index.html.twig
  resources/views/applicant/job_post.html.twig
  resources/views/applicant/manager.html.twig
  resources/views/applicant/profile_01_about.html.twig
  resources/views/applicant/profile_02_experience.html.twig
  resources/views/applicant/profile_03_skills.html.twig
  resources/views/applicant/profile_04_references.html.twig
  resources/views/applicant/profile_05_portfolio.html.twig
  resources/views/applicant/static_credentialing.html.twig
  resources/views/applicant/static_faq.html.twig
  resources/views/common/head.html.twig
  resources/views/common/home/hero.html.twig
  resources/views/layouts/app.blade.php
  resources/views/layouts/base.html.twig
  resources/views/manager/applicant_profile.html.twig
  resources/views/manager/application_post.html.twig
  resources/views/manager/home.html.twig
  resources/views/manager/job_create.html.twig
  resources/views/manager/job_index.html.twig
  resources/views/manager/profile.html.twig
  resources/views/manager/screening-plan.html.twig
Labels: Accessibility, Front-end, Medium Complexity

#680 Adds Application Step 6
  app/Http/Controllers/ApplicationByJobController.php
  app/Http/ViewComposers/ApplicationTrackerComposer.php
  app/Models/JobApplication.php
  public/css/app.css
  public/mix-manifest.json
  resources/assets/sass/app.scss
  resources/assets/sass/components/applicant/application/post/_step-06.scss
  resources/assets/sass/system/grid.scss
  resources/lang/en/applicant/application_template.php
  resources/lang/en/applicant/application_tracker.php
  resources/lang/fr/applicant/application_template.php
  resources/lang/fr/applicant/application_tracker.php
  resources/views/applicant/application_post/common/tracker-ajax.html.twig
  resources/views/applicant/application_post/common/tracker.html.twig
  resources/views/applicant/application_post/step_05/signature.html.twig
  resources/views/applicant/application_post/step_05/view_05_actions.html.twig
  resources/views/applicant/application_post_05.html.twig
  resources/views/applicant/application_post_06.html.twig
  routes/web.php
Labels: Accessibility, Back-end, Front-end, Medium Complexity

#699 Addresses UI Fixes with Step 05
  public/css/app.css
  public/js/app.js
  public/mix-manifest.json
  resources/assets/sass/components/applicant/application/post/_step-06.scss
  resources/assets/sass/components/common/application/_view.scss
  resources/lang/en/applicant/application_template.php
  resources/lang/fr/applicant/job_post.php
  resources/views/applicant/application_post_06.html.twig
  resources/views/common/application/view/view_01_about.html.twig
  resources/views/common/application/view/view_02_experience.html.twig
  resources/views/common/application/view/view_03_essential.html.twig
  resources/views/common/application/view/view_04_asset.html.twig
  resources/views/common/application/view/view_layout.html.twig
Labels: Bug, Front-end, Low Complexity

#748 Display Last Full Day to apply on Job Posters
  app/Helpers/Helper.php
  config/app.php
  config/twigbridge.php
  resources/views/applicant/job_index/index.html.twig
  resources/views/applicant/job_post/header.html.twig
  tests/Unit/Helpers/HelperTest.php
Labels: Back-end, Front-end, Low Complexity
