Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-05, with the labels that each got.

#930 Update FAQ 'Things to Know' with new copy
  resources/lang/en/applicant/faq.php
  resources/lang/fr/applicant/faq.php
Labels: Copy, Front-end

#928 Misc copy issue fixes
  package-lock.json
  resources/lang/en/applicant/application_template.php
  resources/lang/en/common/relatives.php
  resources/lang/en/manager/job_index.php
  resources/lang/en/manager/menu.php
  resources/lang/fr/applicant/application_index.php
  resources/lang/fr/applicant/application_template.php
Labels: Copy, Front-end

#924 remove duplicate X-Frame-Options header
  app/Http/Middleware/FullFrameGuard.php
  etc/nginx/default.conf
Labels: Back-end, Bug

#908 Manager not created after role change
  .vscode/settings.json
  app/Exceptions/AdminException.php
  app/Exceptions/Handler.php
  app/Http/Controllers/JobController.php
  app/Listeners/CheckUserRole.php
  app/Providers/EventServiceProvider.php
  resources/views/errors/admin.html.twig
  resources/views/errors/default.html.twig
  resources/views/manager/job_create/form.html.twig
  tests/Feature/AdminPortalTest.php
  tests/Feature/JobControllerTest.php
  tests/Feature/LoginControllerTest.php
  tests/Feature/ReferencesControllerTest.php
  tests/Feature/RegisterControllerTest.php
  tests/Unit/Lang/BaseTranslationTest.php
  tests/Unit/Lang/LangFilesTest.php
Labels: Back-end, Bug

#931 Heading levels sitewide
  resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
  resources/assets/sass/components/applicant/job/index/_index.scss
  resources/assets/sass/components/applicant/profile/_header.scss
  resources/assets/sass/components/common/_header.scss
  resources/assets/sass/components/manager/job_create/_form.scss
  resources/assets/sass/system/typography.scss
  resources/views/applicant/job_index/index.html.twig
  resources/views/applicant/job_post/apply.html.twig
  resources/views/applicant/job_post/basics.html.twig
  resources/views/applicant/job_post/criteria.html.twig
  resources/views/applicant/job_post/culture.html.twig
  resources/views/applicant/job_post/extras.html.twig
  resources/views/applicant/job_post/header.html.twig
  resources/views/applicant/job_post/impact.html.twig
  resources/views/applicant/job_post/language.html.twig
  resources/views/applicant/job_post/sidebar.html.twig
  resources/views/applicant/job_post/work.html.twig
  resources/views/applicant/manager/header.html.twig
  resources/views/applicant/profile/header.html.twig
  resources/views/common/header.html.twig
  resources/views/manager/applicant_profile.html.twig
  resources/views/manager/job_create/form.html.twig
  resources/views/manager/job_create/sidebar.html.twig
  resources/views/manager/job_index/index.html.twig
  resources/views/manager/job_index/job.html.twig
  resources/views/manager/job_index/layout.html.twig
  resources/views/manager/job_index/sidebar.html.twig
  resources/views/manager/profile/about.html.twig
  resources/views/manager/profile/culture.html.twig
  resources/views/manager/profile/environment.html.twig
  resources/views/manager/profile/header.html.twig
  resources/views/manager/profile/leadership.html.twig
  resources/views/manager/profile/sidebar.html.twig
Labels: Accessibility, Front-end
