Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-11, with the labels that each got.

#1885 Update symfony packages to 4.3.6
  composer.lock
Labels: Dependency, PHP

#1933 Add new classification code
  resources/assets/js/components/ApplicationReview/helpers.ts
  resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.tsx
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/components/JobDetails/JobDetailsMessages.tsx
  resources/assets/js/models/lookupConstants.ts
  tests/Browser/3-builder.testcafe.js
Labels: Back-end, Low Complexity

#1938 Fixes 'Submit Feedback' link and various accessibility issues
  app/Http/Controllers/JobBuilderController.php
  resources/lang/en/manager/job_builder.php
  resources/lang/en/manager/menu.php
  resources/lang/fr/manager/job_builder.php
  resources/lang/fr/manager/menu.php
  resources/views/applicant/application_post/step_01/questions.html.twig
  resources/views/applicant/application_post_02.html.twig
  resources/views/common/alert.html.twig
  resources/views/common/modals/skills_need_help.html.twig
  resources/views/manager/job-builder-root.html.twig
  resources/views/manager/profile/about.html.twig
  resources/views/manager/profile/account.html.twig
Labels: Accessibility, Front-end

#1953 HR Portal - Add hr_advisor role and model
  app/Models/HrAdvisor.php
  app/Models/User.php
  database/factories/UserFactory.php
  database/migrations/2019_11_07_180655_add_hr_advisor_to_user_roles.php
Labels: Back-end, Low Complexity

#1957 Fix manager FAQ notification links
  resources/lang/en/applicant/faq.php
  resources/lang/en/manager/job_index.php
  resources/lang/en/manager/notification.php
  resources/lang/fr/applicant/faq.php
  resources/lang/fr/manager/job_index.php
  resources/lang/fr/manager/notification.php
  resources/views/manager/job_index.html.twig
  resources/views/manager/notification.html.twig
  routes/web.php
Labels: Front-end

#2034 [Security] Bulk update symfony packages to 4.3.8
  composer.lock
Labels: Dependency, PHP, Security

#2035 Rework JPB component folder structure
  resources/assets/js/components/JobBuilder/Details/JobDetails.tsx
  resources/assets/js/components/JobBuilder/Details/JobDetailsMessages.tsx
  resources/assets/js/components/JobBuilder/Details/JobDetailsPage.tsx
  resources/assets/js/components/JobBuilder/Impact/JobBuilderImpact.tsx
  resources/assets/js/components/JobBuilder/Impact/JobBuilderImpactPage.tsx
  resources/assets/js/components/JobBuilder/Impact/JobImpactPreview.tsx
  resources/assets/js/components/JobBuilder/Intro/IntroForm.tsx
  resources/assets/js/components/JobBuilder/Intro/JobBuilderIntro.tsx
  resources/assets/js/components/JobBuilder/JobBuilderRoot.tsx
  resources/assets/js/components/JobBuilder/Review/JobReview.tsx
  resources/assets/js/components/JobBuilder/Review/JobReviewPage.tsx
  resources/assets/js/components/JobBuilder/Skills/CriteriaForm.test.ts
  resources/assets/js/components/JobBuilder/Skills/CriteriaForm.tsx
  resources/assets/js/components/JobBuilder/Skills/JobBuilderSkills.test.ts
  resources/assets/js/components/JobBuilder/Skills/JobBuilderSkills.tsx
  resources/assets/js/components/JobBuilder/Skills/JobBuilderSkillsPage.tsx
  resources/assets/js/components/JobBuilder/Tasks/JobTasks.tsx
  resources/assets/js/components/JobBuilder/Tasks/JobTasksPage.tsx
  resources/assets/js/components/JobBuilder/WorkEnv/JobBuilderWorkEnv.tsx
  resources/assets/js/components/JobBuilder/WorkEnv/WorkEnvForm.tsx
  resources/assets/js/components/JobBuilder/WorkEnv/WorkEnvModal.tsx
  resources/assets/js/stories/JobPosterBuilder/Details.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Impact.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Intro.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Review.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Skills.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Tasks.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/WorkEnvironment.stories.tsx
Labels: Low Complexity, Refactor

#1955 HR Portal - Login and registration
  .env.example
  .env.testing
  .env.travis
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/FirstVisitController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/HomepageController.php
  app/Http/Kernel.php
  app/Http/Middleware/Authenticate.php
  app/Http/Middleware/CheckRole.php
  app/Http/Middleware/FinishHrRegistration.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Http/ViewComposers/MenuComposer.php
  app/Models/HrAdvisor.php
  app/Models/User.php
  app/Services/Validation/RegistrationValidator.php
  app/Services/WhichPortal.php
  config/app.php
  database/factories/UserFactory.php
  database/migrations/2019_11_07_230457_add_hr_advisor_table.php
  database/seeds/DevSeeder.php
  database/seeds/UsersSeeder.php
  resources/lang/en/common/auth/first_hr_visit.php
  resources/lang/en/hr_advisor/home.php
  resources/lang/en/hr_advisor/menu.php
  resources/lang/fr/common/auth/first_hr_visit.php
  resources/lang/fr/hr_advisor/home.php
  resources/lang/fr/hr_advisor/menu.php
  resources/views/hr_advisor/home.html.twig
  routes/web.php
Labels: Back-end, Medium Complexity

#2010 Resolve Jest dependency vulnerability
  package-lock.json
Labels: Dependency, Low Complexity, NPM

#2038 Remove outdated info from readme.md
  README.md
Labels: Copy

#2009 Get rid of console error about browserslist config
  .browserslistrc
  webpack.mix.js
Labels: Low Complexity

#2047 Claimed jobs API routes for HR advisors
  app/Http/Controllers/Api/ClaimJobApiController.php
  app/Models/HrAdvisor.php
  app/Models/JobPoster.php
  database/migrations/2019_11_12_222800_add_claimed_jobs_pivot_table.php
  routes/web.php
  tests/Feature/ClaimJobApiControllerTest.php
Labels: Back-end, Medium Complexity

#2040 Add JobCard display component for various index pages
  resources/assets/js/components/JobCard.tsx
  resources/assets/js/stories/JobCard.stories.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobCard.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end, Low Complexity

#2071 Fix npm audit vulnerability in jest
  package-lock.json
Labels: Dependency, NPM, Priority, Security

#2119 Update symfony framework to 4.4.0
  composer.lock
Labels: Dependency, PHP

#2139 Change copy for submit button on JPB Review page
  resources/assets/js/components/JobBuilder/Review/JobReview.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
  tests/Browser/3-builder.testcafe.js
Labels: Copy

#2138 Remove lang IDs from Review Applicants
  resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
Labels: Front-end, Low Complexity

#2137 Fix 'Edit Profile' link (Manager page, Admin portal)
  app/Http/Controllers/Admin/ManagerCrudController.php
  app/Http/Controllers/Auth/FirstVisitController.php
  app/Http/Middleware/FinishManagerRegistration.php
  resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php
Labels: Back-end, Low Complexity
