Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-07, with the labels that each got.

#1084 Job Poster Builder - Job Details - Adds Localization and Translations
  resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.tsx
  resources/assets/js/components/JobBuilderWorkEnv/WorkEnvModal.tsx
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/models/localizedConstants.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/Form/Messages.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderWorkEnv/WorkEnvModal.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end

#1089 Update department list (FAQ)
  resources/lang/en/applicant/faq.php
  resources/lang/fr/applicant/faq.php
Labels: Copy

#1083 Update NPM/Composer dependencies
  .travis.yml
  .vscode/settings.json
  Makefile
  app/Exceptions/Handler.php
  app/Http/Controllers/ApplicantProfileController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Models/BackpackUser.php
  app/Models/Criteria.php
  app/Models/JobPoster.php
  app/Models/JobPosterKeyTask.php
  app/Models/JobPosterQuestion.php
  app/Models/Lookup/ApplicationStatus.php
  app/Models/Lookup/CitizenshipDeclaration.php
  app/Models/Lookup/CriteriaType.php
  app/Models/Lookup/Department.php
  app/Models/Lookup/ExperienceLevel.php
  app/Models/Lookup/FileType.php
  app/Models/Lookup/JobTerm.php
  app/Models/Lookup/LanguageRequirement.php
  app/Models/Lookup/Province.php
  app/Models/Lookup/Relationship.php
  app/Models/Lookup/SecurityClearance.php
  app/Models/Lookup/SkillLevel.php
  app/Models/Manager.php
  app/Models/TeamCulture.php
  app/Models/TeamCultureTranslation.php
  app/Models/User.php
  app/Models/UserRole.php
  app/Models/WorkEnvironment.php
  app/Services/Validation/Requests/UpdateApplicationProfileValidator.php
  app/Services/Validation/Rules/ApplicantHasRelationRule.php
  app/Services/Validation/Rules/PasswordCorrectRule.php
  app/Services/Validation/Rules/SkillDeclarationBelongsToUserRule.php
  app/Services/Validation/Rules/UniqueApplicantSkillRule.php
  composer.json
  composer.lock
  database/factories/UserFactory.php
  etc/nginx/default.conf
  package-lock.json
  package.json
  tests/Feature/LoginControllerTest.php
  tests/Unit/Lang/BaseTranslationTest.php
  tests/Unit/Lang/LangFilesTest.php
  tests/Unit/Validators/UpdateApplicationProfileValidatorTest.php
Labels: Back-end

#1146 Fix Modal rendering/scrolling issues
  resources/assets/js/components/JobBuilderImpact/JobBuilderImpact.tsx
  resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.tsx
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/components/Modal.tsx
Labels: Bug, Front-end

#1119 Add Job Poster Builder Tasks page (component only)
  package-lock.json
  package.json
  resources/assets/js/components/Form/TextAreaInput.tsx
  resources/assets/js/components/JobTasks/JobTasks.tsx
  resources/assets/js/fakeData/fakeJob.ts
  resources/assets/js/models/jobUtil.ts
  resources/assets/js/models/types.ts
  resources/assets/js/stories/JobPosterBuilder/Tasks.stories.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobTasks/JobTasks.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end, Medium Complexity

#1149 Bugfix/skill help modal
  resources/assets/js/components/ApplicantSkills/SkillsInfoModal.tsx
  resources/assets/sass/components/applicant/application/post/_skill-layout.scss
  resources/assets/sass/components/common/_forms.scss
  resources/assets/sass/components/common/skills/_common.scss
  resources/lang/en/applicant/profile_skills.php
  resources/lang/en/common/skills.php
  resources/lang/fr/applicant/profile_skills.php
  resources/lang/fr/common/skills.php
  resources/views/applicant/profile/skills/index.html.twig
  resources/views/common/scripts.html.twig
  resources/views/common/skill.html.twig
Labels: Bug, Front-end

#1143 Feature/job builder/update job detail modal content
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/components/JobPreview.tsx
  resources/assets/js/fakeData/fakeJob.ts
  resources/assets/js/stories/JobPosterBuilder/Preview.stories.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobPreview.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end
