Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-10, with the labels that each got.

#1555 Clean up eslint errors
  resources/assets/js/components/AssessmentPlan/AssessmentPlanBuilder.tsx
  resources/assets/js/components/AssessmentPlan/RatingGuideBuilder.tsx
  resources/assets/js/components/AssessmentPlan/RatingGuideQuestion.tsx
  resources/assets/js/components/AssessmentPlan/RatingGuideQuestionWithAnswers.tsx
  resources/assets/js/components/ErrorToast.tsx
  resources/assets/js/components/InfoModal.tsx
  resources/assets/js/components/JobBuilderSkills/CriteriaForm.test.ts
  resources/assets/js/components/WordCounter/WordCounter.tsx
  resources/assets/js/components/WordCounter/WordCounterWrapper.tsx
  resources/assets/js/fakeData/fakeJob.ts
  resources/assets/js/fakeData/fakeRatingGuideAnswer.ts
  resources/assets/js/helpers/router.ts
  resources/assets/js/managerRegistration.ts
  resources/assets/js/models/app.ts
  resources/assets/js/models/localizedConstants.test.ts
  resources/assets/js/store/Assessment/assessmentActions.ts
  resources/assets/js/store/Assessment/assessmentReducer.test.ts
  resources/assets/js/store/Assessment/assessmentSelectorComplex.ts
  resources/assets/js/store/AssessmentPlan/assessmentPlanActions.ts
  resources/assets/js/store/AssessmentPlanNotification/assessmentPlanNotificationActions.ts
  resources/assets/js/store/AssessmentPlanNotification/assessmentPlanNotificationSelectors.ts
  resources/assets/js/store/Job/jobActions.test.ts
  resources/assets/js/store/Job/jobSelectorComplex.ts
  resources/assets/js/store/RatingGuideAnswer/ratingGuideAnswerActions.ts
  resources/assets/js/store/RatingGuideAnswer/ratingGuideAnswerSelectors.ts
  resources/assets/js/store/RatingGuideQuestion/ratingGuideQuestionActions.ts
  resources/assets/js/store/Skill/skillActions.ts
  resources/assets/js/store/createAction.ts
  resources/assets/js/stories/JobPosterBuilder/Review.stories.tsx
  resources/assets/js/stories/WordCounter/WordCounter.stories.tsx
Labels: Front-end, Low Complexity

#1606 Generate new SRI hash for html2canvas
  resources/views/common/head.html.twig
Labels: Bug, Low Complexity

#1695 Copy change: 'Average Annual Salary'
  resources/assets/js/components/JobReview/JobReview.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
  resources/lang/en/applicant/job_index.php
  resources/lang/fr/applicant/job_index.php
  resources/views/manager/builder-08.html.twig
Labels: Copy, Low Complexity

#1691 Remove hardcoded English copy from React files
  resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.tsx
  resources/assets/js/components/CopyToClipboardButton.tsx
  resources/assets/js/components/JobBuilder/Criterion.tsx
  resources/assets/js/components/JobBuilder/JobWorkCulture.tsx
  resources/assets/js/components/JobBuilderImpact/JobBuilderImpact.tsx
  resources/assets/js/components/JobBuilderImpact/JobImpactPreview.tsx
  resources/assets/js/components/JobBuilderSkills/CriteriaForm.tsx
  resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.tsx
  resources/assets/js/components/JobReview/JobReview.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/ApplicationReview/ReviewApplications.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/AssessmentPlan/AssessmentPlanAlert.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/AssessmentPlan/AssessmentPlanTable.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/AssessmentPlan/RatingGuideMissing.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/CopyToClipboardButton.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/Criterion.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/JobBasicInfo.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/JobWorkCulture.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderImpact/JobBuilderImpact.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderImpact/JobImpactPreview.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderIntro/IntroForm.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderSkills/CriteriaForm.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderWorkEnv/WorkEnvModal.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobDetails/JobDetailsMessages.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobPreview.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobTasks/JobTasks.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/models/localizedConstants.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Copy, Low Complexity, Refactor

#1721 Fix issue with password confirmation naming
  resources/views/auth/passwords/reset.html.twig
Labels: Bug, Front-end, Priority

#1723 Display hire_impact on job preview cards (homepage)
  resources/views/applicant/home.html.twig
Labels: Bug, Low Complexity

#1751 Replace tightenco/parental with calebporzio/parental
  app/Models/BackpackUser.php
  composer.json
  composer.lock
Labels: Dependency, Low Complexity, PHP

#1750 Allow two factor deactivation
  app/Http/Controllers/Auth/TwoFactorController.php
  resources/views/applicant/profile/about/about.html.twig
  routes/web.php
Labels: Back-end, Low Complexity

#1755 Update outdated composer dependencies
  composer.lock
Labels: Dependency, PHP

#1756 Add missing translations to job poster
  resources/lang/fr/applicant/job_post.php
Labels: Copy, Low Complexity

#1776 Add imagemagick package to Dockerfile
  Dockerfile
  docker-compose.yml
Labels: Blocker, Low Complexity

#1753 Split user 'name' into first/last names
  app/Http/Controllers/Admin/JobPosterCrudController.php
  app/Http/Controllers/Admin/ManagerCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/ApplicantProfileController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Requests/UpdateManagerProfileRequest.php
  app/Models/Manager.php
  app/Models/User.php
  app/Services/Validation/RegistrationValidator.php
  app/Services/Validation/Requests/UpdateApplicationProfileValidator.php
  database/factories/UserFactory.php
  database/migrations/2019_10_16_031247_split_username_first_last.php
  database/seeds/DevSeeder.php
  resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
  resources/assets/js/components/ApplicationReview/ApplicationReviewWithNav.tsx
  resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
  resources/assets/js/components/ApplicationReview/helpers.ts
  resources/assets/js/fakeData/fakeManager.ts
  resources/assets/js/models/types.ts
  resources/lang/en/applicant/applicant_profile.php
  resources/lang/en/common/auth/register.php
  resources/lang/en/manager/profile.php
  resources/lang/fr/applicant/applicant_profile.php
  resources/lang/fr/common/auth/register.php
  resources/lang/fr/manager/profile.php
  resources/views/applicant/application_preview.html.twig
  resources/views/applicant/job_post/culture.html.twig
  resources/views/applicant/jpb_job_post/culture.html.twig
  resources/views/applicant/manager/header.html.twig
  resources/views/applicant/profile/about/about.html.twig
  resources/views/applicant/profile/header.html.twig
  resources/views/applicant/profile_03_skills.html.twig
  resources/views/auth/register.html.twig
  resources/views/common/application/view/view_01_about.html.twig
  resources/views/manager/applicant_profile.html.twig
  resources/views/manager/application_post.html.twig
  resources/views/manager/profile/account.html.twig
  resources/views/manager/profile/header.html.twig
  resources/views/manager/review_applications.html.twig
  tests/Feature/ManagerApiControllerTest.php
  tests/Feature/RegisterControllerTest.php
  tests/Unit/Validators/UpdateApplicationProfileValidatorTest.php
Labels: Back-end, Medium Complexity, Refactor

#1796 Remove redundant NPM packages
  package-lock.json
  package.json
Labels: Dependency, NPM

#1778 Manage 2FA via admin portal
  app/Http/Controllers/Admin/TwoFactorCrudController.php
  app/Http/Controllers/Auth/RecoveryCodeController.php
  app/Http/Controllers/Auth/TwoFactorController.php
  app/Http/ViewComposers/TwoFactorComposer.php
  resources/views/auth/two_factor.html.twig
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  resources/views/vendor/backpack/crud/buttons/activate_2fa.blade.php
  resources/views/vendor/backpack/crud/buttons/deactivate_2fa.blade.php
  resources/views/vendor/backpack/crud/buttons/recovery_codes.blade.php
  routes/backpack/custom.php
  routes/web.php
Labels: Back-end, Medium Complexity

#1802 Deactivate 2FA route changed to POST / add 2FA to manager profile
  app/Http/Controllers/Auth/RecoveryCodeController.php
  app/Http/Controllers/Auth/TwoFactorController.php
  app/Http/ViewComposers/TwoFactorComposer.php
  resources/lang/en/applicant/applicant_profile.php
  resources/lang/en/manager/profile.php
  resources/lang/fr/applicant/applicant_profile.php
  resources/lang/fr/manager/profile.php
  resources/views/applicant/profile/about/about.html.twig
  resources/views/applicant/profile_01_about.html.twig
  resources/views/manager/profile.html.twig
  resources/views/manager/profile/account.html.twig
  resources/views/manager/profile/layout.html.twig
  resources/views/vendor/backpack/crud/buttons/deactivate_2fa.blade.php
  routes/web.php
Labels: Back-end, Front-end, Low Complexity

#1798 Admin portal issues
  app/Helpers/Helper.php
  app/Http/Controllers/Admin/DepartmentCrudController.php
  app/Http/Controllers/Admin/JobPosterCrudController.php
  app/Http/Controllers/Admin/ManagerCrudController.php
  app/Http/Controllers/Admin/SkillCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/JobController.php
  app/Models/JobPoster.php
  database/migrations/2019_10_23_175841_add_hr_columns_to_job_poster.php
  resources/views/manager/job_create/form.html.twig
  resources/views/manager/job_create/sidebar.html.twig
  resources/views/vendor/backpack/crud/buttons/job_admin_edit.blade.php
  resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php
  resources/views/vendor/backpack/crud/buttons/spb_link.blade.php
  tests/Feature/JobControllerTest.php
Labels: Back-end, Medium Complexity

#1846 Update Google2FA packages
  composer.lock
Labels: Dependency, PHP
