Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-08, with the labels that each got.

#1178 Remove Firefox from the testcafe-ci script
  .travis.yml
  package.json
  tests/Unit/Helpers/HelperTest.php
Labels: Bug

#1156 Classifications admin panel
  app/Http/Controllers/Admin/ClassificationCrudController.php
  app/Http/Requests/ClassificationCrudRequest.php
  app/Http/Requests/UpdateJobPoster.php
  app/Models/Classification.php
  app/Models/JobPoster.php
  database/factories/JobPosterFactory.php
  database/migrations/2019_07_30_145326_add_classification_id_to_job_posters.php
  database/migrations/2019_07_30_150049_transfer_classification_code_to_classification_id_on_job_posters.php
  database/migrations/2019_07_30_151411_remove_classification_code_from_job_posters.php
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  routes/backpack/custom.php
  tests/Feature/JobApiControllerTest.php
Labels: Back-end, Low Complexity

#1211 Task/more screen plan l10ns
  resources/assets/js/components/JobBuilder/jobBuilderMessages.ts
  resources/assets/js/components/JobBuilderImpact/JobBuilderImpactPage.tsx
  resources/assets/js/components/JobBuilderIntro/JobBuilderIntro.tsx
  resources/assets/js/components/JobBuilderSkills/JobBuilderSkillsPage.tsx
  resources/assets/js/components/JobBuilderWorkEnv/JobBuilderWorkEnv.tsx
  resources/assets/js/components/JobDetails/JobDetailsPage.tsx
  resources/assets/js/components/JobTasks/JobTasksPage.tsx
  resources/assets/js/models/localizedConstants.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/jobBuilderMessages.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderImpact/JobBuilderImpactPage.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderIntro/JobBuilderIntro.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderSkills/JobBuilderSkillsPage.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderWorkEnv/JobBuilderWorkEnv.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobDetails/JobDetailsPage.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobTasks/JobTasksPage.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/models/localizedConstants.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end

#1256 Admin panel ordering / filtering on Skills, Departments
  app/Http/Controllers/Admin/DepartmentCrudController.php
  app/Http/Controllers/Admin/SkillCrudController.php
Labels: Back-end, Low Complexity

#1265 Feature/job builder/skills l10n
  resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
  resources/assets/js/translations/locales/whitelist_fr.json
Labels: Front-end

#1277 Fix intermittent failing Job Poster status test
  database/factories/JobPosterFactory.php
Labels: Back-end, Bug

#1278 Replace Formik array helpers with local equivalents
  resources/assets/js/components/JobTasks/JobTasks.tsx
Labels: Bug, Front-end

#1309 Adds l10ns for Job Poster Review Step
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/components/JobReview/JobReview.tsx
  resources/assets/js/fakeData/fakeJob.ts
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/ApplicantSkills/SkillsWordCounter.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobDetails/JobDetails.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end

#1324 Update critical vulnerability in eslint
  package-lock.json
Labels: Dependency, NPM, Priority
