Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-09, with the labels that each got.

#1378 refactors l10n strings so format is consistent across jobBuilder
  resources/assets/js/components/JobBuilder/JobBasicInfo.tsx
  resources/assets/js/components/JobBuilder/JobWorkCulture.tsx
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/components/JobDetails/JobDetailsMessages.tsx
  resources/assets/js/components/JobPreview.tsx
  resources/assets/js/components/JobTasks/JobTasks.tsx
  resources/assets/js/models/localizedConstants.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/JobBasicInfo.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/JobWorkCulture.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilder/jobBuilderMessages.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderIntro/IntroForm.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobDetails/JobDetails.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobDetails/JobDetailsMessages.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobPreview.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobTasks/JobTasks.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/models/localizedConstants.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
Labels: Front-end

#1388 Update React root templates to include proper headings
  resources/views/common/redux.html.twig
  resources/views/manager/job-builder-root.html.twig
Labels: Front-end, Low Complexity

#1392 Task/add translations
  resources/assets/js/translations/locales/fr.json
  resources/assets/js/translations/locales/whitelist_fr.json
Labels: Front-end, Low Complexity

#1444 Add demo account notification to manager portal
  app/Http/Controllers/JobController.php
  app/Http/Controllers/ManagerProfileController.php
  app/Http/ViewComposers/DemoNotificationComposer.php
  app/Http/ViewComposers/MenuComposer.php
  app/Providers/ViewComposerServiceProvider.php
  resources/assets/sass/app.scss
  resources/assets/sass/components/common/_notification.scss
  resources/lang/en/manager/notification.php
  resources/lang/fr/manager/notification.php
  resources/views/applicant/static_faq.html.twig
  resources/views/manager/job_index.html.twig
  resources/views/manager/notification.html.twig
  resources/views/manager/profile.html.twig
  routes/web.php
  tests/Unit/Lang/LangFilesTest.php
Labels: Front-end, Low Complexity

#1456 Update storybook and addons to 5.2.0
  package-lock.json
  package.json
  resources/assets/js/stories/JobPosterBuilder/Details.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Skills.stories.tsx
Labels: Dependency, NPM

#1430 New manager homepage
  app/Http/Controllers/FaqController.php
  app/Http/Controllers/HomepageController.php
  app/Http/Controllers/ManagerProfileController.php
  public/images/patrick-hendry.jpg
  public/images/sean-pollock.jpg
  resources/assets/sass/app.scss
  resources/assets/sass/components/applicant/home/_how.scss
  resources/assets/sass/components/common/_accordions.scss
  resources/assets/sass/components/common/_sidebar.scss
  resources/assets/sass/components/common/static/_faq.scss
  resources/assets/sass/components/manager/homepage.scss
  resources/lang/en/applicant/faq.php
  resources/lang/en/manager/home.php
  resources/lang/fr/applicant/faq.php
  resources/lang/fr/manager/home.php
  resources/views/applicant/static/credentialing_layout.html.twig
  resources/views/applicant/static/credentialing_sidebar.html.twig
  resources/views/applicant/static_faq.html.twig
  resources/views/common/scripts.html.twig
  resources/views/manager/home.html.twig
  routes/web.php
  tests/Unit/Lang/LangFilesTest.php
Labels: Front-end, Low Complexity

#1503 Check for admin role during manager level check
  app/Models/User.php
Labels: Back-end, Bug

#1520 Edit manager profile button (Admin portal) opens a new tab
  resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php
Labels: Front-end, High Complexity

#1521 Add data-c-dialog-focus attribute to clone modal
  resources/views/applicant/jpb_job_post/culture.html.twig
  resources/views/common/modals/skills_need_help.html.twig
Labels: Front-end, Low Complexity

#1483 Add account upgrade modal to demo account job index
  resources/assets/sass/components/manager/job_index/_index.scss
  resources/lang/en/applicant/faq.php
  resources/lang/en/manager/job_index.php
  resources/lang/fr/manager/job_index.php
  resources/views/manager/job_index.html.twig
  resources/views/manager/job_index/job.html.twig
Labels: Front-end, Low Complexity

#1517 Update Laravel Framework to 6.0
  app/Services/Validation/Rules/ContainsObjectWithAttributeRule.php
  app/Services/Validation/Rules/PassesValidatorRule.php
  composer.json
  composer.lock
  config/models.php
Labels: Dependency, PHP
