Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-03, with the labels that each got.

#754 Feature/login template transition
  .env.example
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  config/twigbridge.php
  public/js/alerts.js
  resources/views/auth/login.blade.php
  resources/views/auth/login.html.twig
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/email.html.twig
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/passwords/reset.html.twig
  resources/views/auth/register.blade.php
  resources/views/auth/register.html.twig
  resources/views/common/scripts.html.twig
Labels: Back-end, Front-end, Low Complexity

#778 Fixes the applicant review UI when a manager is viewing their applica…
  composer.lock
  package-lock.json
  public/js/alerts.js
  resources/assets/sass/components/manager/applicant-review.scss
  resources/assets/sass/components/manager/job_index/_index.scss
Labels: Front-end, Low Complexity

#787 Empty Applicant Profile Answers Handling for Manager portal
  resources/lang/en/manager/applicant_profile.php
  resources/lang/fr/manager/applicant_profile.php
  resources/views/manager/applicant_profile.html.twig
Labels: Front-end, Low Complexity

#749 Case insensitive user emails
  database/migrations/2019_02_26_210634_case_insensitive_emails.php
  package-lock.json
  tests/Feature/LoginControllerTest.php
Labels: Back-end, Bug, Environment

#790 Fix skills not displaying properly on application
  app/Models/Skill.php
  resources/assets/js/app.js
  resources/views/common/skill.html.twig
  routes/web.php
Labels: Back-end, Bug

#794 Language confirmation tweaks
  resources/lang/en/applicant/job_post.php
  resources/lang/fr/applicant/job_post.php
Labels: Bug, Front-end, Low Complexity

#793 Better coverage reports, checks don't fail inexplicably
  .codecov.yml
  codecov.yml
  composer.lock
  etc/php/php.ini
  package-lock.json
Labels: Environment

#792 Slacktee in builds (sends Lighthouse crawl results to Slack)
  .travis.yml
  composer.lock
  etc/php/php.ini
  etc/scripts/install-slacktee.sh
  etc/scripts/lightcrawler-index.js
  etc/scripts/slacktee.sh
  package-lock.json
  package.json
Labels: Accessibility

#791 Refactor typescript files to fulfil eslint rules
  .eslintrc.json
  .vscode/settings.json
  package-lock.json
  package.json
  resources/assets/js/components/ApplicationReview/ApplicantBucket.tsx
  resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
  resources/assets/js/components/ApplicationReview/ApplicationReviewContainer.tsx
  resources/assets/js/components/ApplicationReview/ReviewApplications.tsx
  resources/assets/js/components/ApplicationReview/ReviewApplicationsContainer.tsx
  resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
  resources/assets/js/components/ApplicationReview/helpers.ts
  resources/assets/js/components/JobPoster.js
  resources/assets/js/components/Reference.jsx
  resources/assets/js/components/ReferenceList.jsx
  resources/assets/js/components/Select.tsx
  resources/assets/js/components/types.ts
  resources/assets/js/helpers/queries.ts
  resources/assets/js/ziggy.js
  webpack.mix.js
Labels: Front-end
