Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-12, with the labels that each got.

#2191 Change formatting of close times on Application index.
  resources/views/applicant/application_index/application.html.twig
Labels: Front-end, Low Complexity

#2075 Jest code coverage / JUnit support / config tweaks
  .env.travis
  .scrutinizer.yml
  .travis.yml
  Makefile
  jest.config.js
  package-lock.json
  package.json
  phpunit.xml
Labels: Back-end, Medium Complexity

#2196 Change copy on JPB Intro form labels
  resources/assets/js/components/JobBuilder/Intro/IntroForm.tsx
  resources/assets/js/fakeData/fakeManager.ts
  resources/assets/js/models/types.ts
  resources/assets/js/translations/locales/fr.json
Labels: Copy

#1915 Add device memory to 2FA flow
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/TwoFactorController.php
  app/Http/Middleware/Google2FA.php
  app/Models/Manager.php
  app/Models/User.php
  app/Traits/RememberDeviceTrait.php
  app/Traits/TalentCloudCrudTrait.php
  config/google2fa.php
  database/migrations/2019_11_22_152802_add_remember_device_token_to_users_table.php
  resources/lang/en/one_time_password.php
  resources/lang/fr/one_time_password.php
  resources/views/auth/one_time_password.html.twig
  resources/views/auth/otp_input.html.twig
  resources/views/auth/two_factor.html.twig
  tests/Unit/Traits/RememberDeviceTraitTest.php
Labels: Back-end, Front-end, Medium Complexity

#2077 User settings with 2FA
  app/Http/Controllers/ApplicantProfileController.php
  app/Http/Controllers/Auth/RecoveryCodeController.php
  app/Http/Controllers/Auth/TwoFactorController.php
  app/Http/Controllers/SettingsController.php
  app/Http/ViewComposers/MenuComposer.php
  app/Policies/UserPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Services/Validation/PasswordValidator.php
  app/Services/Validation/Requests/UpdateApplicationProfileValidator.php
  app/Services/Validation/Rules/PasswordFormatRule.php
  app/Services/WhichPortal.php
  package-lock.json
  resources/assets/sass/app.scss
  resources/lang/en/applicant/applicant_profile.php
  resources/lang/en/applicant/menu.php
  resources/lang/en/common/auth/recovery_codes.php
  resources/lang/en/common/login_modals.php
  resources/lang/en/common/settings.php
  resources/lang/en/manager/menu.php
  resources/lang/en/manager/profile.php
  resources/lang/en/success.php
  resources/lang/en/two_factor.php
  resources/lang/fr/applicant/applicant_profile.php
  resources/lang/fr/applicant/menu.php
  resources/lang/fr/common/auth/recovery_codes.php
  resources/lang/fr/common/login_modals.php
  resources/lang/fr/common/settings.php
  resources/lang/fr/manager/menu.php
  resources/lang/fr/manager/profile.php
  resources/lang/fr/success.php
  resources/lang/fr/two_factor.php
  resources/views/applicant/profile/about/about.html.twig
  resources/views/applicant/profile_01_about.html.twig
  resources/views/applicant/static_faq.html.twig
  resources/views/auth/recovery_codes.html.twig
  resources/views/auth/two_factor.html.twig
  resources/views/common/menu.html.twig
  resources/views/common/settings.html.twig
  resources/views/errors/form_errors.html.twig
  resources/views/manager/profile/account.html.twig
  resources/views/manager/profile/header.html.twig
  resources/views/manager/profile/layout.html.twig
  resources/views/manager/profile/sidebar.html.twig
  routes/web.php
  tests/Browser/2-critical.testcafe.js
  tests/Feature/SettingsControllerTest.php
  tests/Unit/Lang/LangFilesTest.php
  tests/Unit/Validators/UpdateApplicationProfileValidatorTest.php
Labels: Back-end, Medium Complexity, Refactor

#2272 Fix breaking change in PHP code standard update
  ruleset.xml
Labels: Bug, Dependency, PHP

#2195 Replace classification accessor on Job Posters with 1-n relationship
  app/Http/Controllers/JobController.php
  app/Http/Requests/UpdateJobPoster.php
  app/Models/Classification.php
  app/Models/JobPoster.php
  database/factories/JobPosterFactory.php
  database/migrations/2019_11_29_030308_delete_classification_job_posters.php
  resources/assets/js/components/JobBuilder/Details/JobDetails.tsx
  resources/assets/js/components/JobBuilder/Details/JobDetailsMessages.tsx
  resources/assets/js/components/JobBuilder/Review/JobReview.tsx
  resources/assets/js/components/JobBuilder/Skills/JobBuilderSkills.tsx
  resources/assets/js/components/JobBuilder/jobBuilderHelpers.ts
  resources/assets/js/components/JobPreview.tsx
  resources/assets/js/fakeData/fakeJob.ts
  resources/assets/js/models/jobUtil.ts
  resources/assets/js/models/localizedConstants.tsx
  resources/assets/js/models/lookupConstants.ts
  resources/assets/js/models/types.ts
  resources/assets/js/stories/JobPosterBuilder/Details.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/Skills.stories.tsx
  resources/views/applicant/jpb_job_post/basics.html.twig
  resources/views/manager/job_index/job.html.twig
  tests/Browser/3-builder.testcafe.js
  tests/Feature/JobApiControllerTest.php
  tests/Unit/JobPosterTest.php
Labels: Back-end, Medium Complexity, Refactor

#2293 Fix required asterisks on radio elements
  resources/assets/js/app.js
Labels: Bug, Front-end, Low Complexity

#2367 Add PSPC to partner departments (FAQ)
  resources/lang/en/applicant/faq.php
  resources/lang/fr/applicant/faq.php
Labels: Copy

#2435 Update all Symfony packages to 4.4.2
  composer.lock
Labels: Dependency, PHP
