Repository GCTC-NTGC/TalentCloud, pull requests merged in 2019-06, with the labels that each got.

#1005 Fix issue with Skill Declaration ajax update
  app/Http/Controllers/SkillDeclarationController.php
  app/Models/SkillDeclaration.php
  tests/Feature/SkillDeclarationControllerTest.php
Labels: Back-end, Bug, Priority

#1007 Add classification string field to Job Poster factory
  database/factories/JobPosterFactory.php
Labels: Back-end, Low Complexity

#1006 Update PHP formatting in controllers
  app/Http/Controllers/Admin/JobPosterCrudController.php
  app/Http/Controllers/Admin/ManagerCrudController.php
  app/Http/Controllers/Admin/SkillCrudController.php
  app/Http/Controllers/Admin/UserCrudController.php
  app/Http/Controllers/Api/JobApiController.php
  app/Http/Controllers/Api/ManagerApiController.php
  app/Http/Controllers/ApplicantProfileController.php
  app/Http/Controllers/ApplicationByJobController.php
  app/Http/Controllers/ApplicationController.php
  app/Http/Controllers/ApplicationReviewController.php
  app/Http/Controllers/AssessmentController.php
  app/Http/Controllers/AssessmentPlanController.php
  app/Http/Controllers/AssessmentPlanNotificationController.php
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Controllers/Controller.php
  app/Http/Controllers/CourseController.php
  app/Http/Controllers/DegreeController.php
  app/Http/Controllers/ExperienceController.php
  app/Http/Controllers/HomepageController.php
  app/Http/Controllers/JobController.php
  app/Http/Controllers/ManagerProfileController.php
  app/Http/Controllers/RatingGuideAnswerController.php
  app/Http/Controllers/RatingGuideQuestionController.php
  app/Http/Controllers/ReferencesController.php
  app/Http/Controllers/SkillController.php
  app/Http/Controllers/SkillDeclarationController.php
  app/Http/Controllers/WorkExperienceController.php
  app/Http/Controllers/WorkSamplesController.php
  app/Models/JobPoster.php
  routes/web.php
  ruleset.xml
Labels: Back-end, Low Complexity

#1014 Wrap generated text with HTML entity escaping function
  tests/Feature/ReferencesControllerTest.php
Labels: Back-end, Bug

#1017 Restore manager select element styles
  resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
  resources/assets/js/components/ApplicationReview/ApplicationReviewWithNav.tsx
Labels: Bug

#1016 Remove work environment demo code
  resources/views/applicant/job_post/culture.html.twig
Labels: Bug

#913 Download all applications as PDFs
  etc/nginx/default.conf
  resources/assets/js/components/ApplicationReview/ApplicationReviewWithNav.tsx
  resources/assets/js/getpdf.js
  resources/views/common/application/view/view_layout.html.twig
  resources/views/common/head.html.twig
  webpack.mix.js
Labels: Back-end, Priority

#1024 Add blockcert url field to degrees
  app/Http/Controllers/ApplicationByJobController.php
  app/Http/Controllers/ExperienceController.php
  app/Models/Degree.php
  app/Models/WorkExperience.php
  database/migrations/2019_06_11_211530_add_blockcert_url_to_degrees.php
  resources/lang/en/common/degree.php
  resources/lang/fr/common/degree.php
  resources/views/common/degree.html.twig
Labels: Priority

#1023 Test cafe integrated with CI
  .env.travis
  .travis.yml
  composer.lock
  package-lock.json
  package.json
  tests/Browser/Pages/HomePage.php
  tests/Browser/Pages/Page.php
  tests/Browser/ProfileTest.php
  tests/Browser/RegisterTest.php
  tests/Browser/StaticPagesTest.php
  tests/Browser/smoke.testcafe
  tests/Browser/smoke.testcafe.js
Labels: Back-end

#1026 Cleanup Team Culture formatting on Job Poster
  resources/assets/sass/components/applicant/job/post/_culture.scss
  resources/views/applicant/job_post/culture.html.twig
  resources/views/applicant/manager/header.html.twig
  resources/views/applicant/profile/header.html.twig
  resources/views/manager/profile/header.html.twig
Labels: Front-end

#1008 Job Poster Builder step 01 components
  .storybook/addons.js
  .storybook/config.ts
  package-lock.json
  package.json
  resources/assets/js/components.tsx
  resources/assets/js/components/Form/Messages.tsx
  resources/assets/js/components/Form/RadioGroup.tsx
  resources/assets/js/components/Form/RadioInput.tsx
  resources/assets/js/components/Form/SelectInput.tsx
  resources/assets/js/components/Form/TextInput.tsx
  resources/assets/js/components/Input.tsx
  resources/assets/js/components/JobDetails/JobDetails.tsx
  resources/assets/js/components/JobPreview.tsx
  resources/assets/js/components/Modal.tsx
  resources/assets/js/components/Select.tsx
  resources/assets/js/components/UpdatingInput.tsx
  resources/assets/js/components/__snapshots__/Input.test.tsx.snap
  resources/assets/js/stories/Input.stories.tsx
  resources/assets/js/stories/JobPosterBuilder/JobDetails.stories.tsx
  resources/assets/js/stories/JobPreview.stories.tsx
  resources/assets/js/stories/Modal.stories.tsx
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/Form/Messages.json
  resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobDetails/JobDetails.json
  resources/assets/js/translations/locales/defaultMessages.json
  resources/assets/js/translations/locales/fr.json
  resources/views/common/head.html.twig
  resources/views/manager/builder-02.html.twig
Labels: Front-end, Medium Complexity, Priority

#1044 Add missing variable declaration to language_requirement condition
  resources/views/common/application/view/view_01_about.html.twig
Labels: Front-end

#1045 fixes Prince Edward Island translation key typo
  resources/assets/js/models/localizedConstants.tsx
Labels: Bug
