Repository GCTC-NTGC/TalentCloud, pull requests merged in 2020-01, with the labels that each got.

#2488 Travis-CI performance improvements
  .travis.yml
  Makefile
  package.json
  tests/Browser/1-smoke.testcafe.js
  tests/Browser/2-critical.testcafe.js
  tests/Browser/3-builder.testcafe.js
Labels: Back-end, Refactor

#2491 Bug - Restore link to Applicant Review
  app/Http/Controllers/Admin/JobPosterCrudController.php
Labels: Bug, Low Complexity

#2489 HR - Job Summary page
  app/Http/Controllers/JobSummaryController.php
  database/seeds/CommentSeeder.php
  public/images/job-process-summary-tool-applicants.svg
  public/images/job-process-summary-tool-edit.svg
  public/images/job-process-summary-tool-screen.svg
  public/images/job-process-summary-tool-view.svg
  resources/assets/sass/app.scss
  resources/assets/sass/components/common/job-process-summary.scss
  resources/lang/en/hr_advisor/home.php
  resources/lang/en/hr_advisor/job_summary.php
  resources/lang/en/hr_advisor/menu.php
  resources/lang/fr/hr_advisor/home.php
  resources/lang/fr/hr_advisor/job_summary.php
  resources/lang/fr/hr_advisor/menu.php
  resources/views/hr_advisor/job_index.html.twig
  resources/views/hr_advisor/job_summary.html.twig
  routes/web.php
Labels: Front-end, Medium Complexity

#2555 Upgrade babel/storybook/core-js
  package-lock.json
  package.json
Labels: Dependency, NPM

#2539 Config tweaks / optimization
  .babelrc
  .codecov.yml
  .env.example
  .env.testing
  .env.travis
  .eslintrc.json
  .gitignore
  .prettierrc.json
  .scrutinizer.yml
  .scss-lint.yml
  .travis.yml
  Makefile
  composer.json
  composer.lock
  config/app.php
  gulpfile.js
  jest.config.js
  jest.setup.js
  package.json
  phpunit.xml
  resources/lang/en/manager/profile.php
  snippets.html.twig
  tests/Browser/smoke.testcafe
  tests/Unit/Lang/LangFilesTest.php
  tsconfig.json
Labels: Refactor

#2579 Bulk update NPM packages
  package-lock.json
  package.json
Labels: Dependency

#2541 HR - Access to submitted applications and profiles
  app/Http/Controllers/ApplicationController.php
  app/Http/Controllers/JobSummaryController.php
  app/Models/Applicant.php
  app/Policies/ApplicantPolicy.php
  app/Policies/ApplicationPolicy.php
  database/factories/JobPosterFactory.php
  database/factories/UserFactory.php
  database/seeds/DevSeeder.php
  resources/assets/js/helpers/routes.ts
  resources/views/hr_advisor/job_summary.html.twig
  resources/views/hr_advisor/summary_action_card.html.twig
  routes/web.php
Labels: Front-end, Low Complexity

#2660 HR Job Summary - Replace list of applicants with the number of applicants
  resources/lang/en/hr_advisor/job_summary.php
  resources/lang/fr/hr_advisor/job_summary.php
  resources/views/hr_advisor/job_summary.html.twig
Labels: Front-end, Low Complexity

#2672 HR Portal - Homepage Content
  resources/assets/sass/app.scss
  resources/assets/sass/components/hr/home.scss
  resources/lang/en/hr_advisor/home.php
  resources/lang/fr/hr_advisor/home.php
  resources/views/hr_advisor/home.html.twig
Labels: Copy

#2687 HR Index - Edit menu styling
  resources/views/hr_advisor/job_index.html.twig
Labels: Front-end, Low Complexity

#2703 Add new SRI hash to script, add image source to CSP
  etc/nginx/default.conf
  resources/views/common/head.html.twig
Labels: Bug, Low Complexity

#2721 Final tweaks added for prod deployment
  resources/assets/js/components/HRPortal/JobIndexHr.tsx
  resources/assets/js/components/HRPortal/JobIndexHrPage.tsx
  resources/assets/js/components/HRPortal/__snapshots__/JobIndexHr.test.tsx.snap
  resources/assets/js/components/HRPortal/fixtures.tsx
  resources/assets/js/components/JobCard.tsx
  resources/assets/js/components/UnclaimedJobCard.tsx
  resources/assets/js/stories/JobCard.stories.tsx
  resources/assets/js/stories/UnclaimedJobCard.stories.tsx
  resources/views/applicant/application_index/application.html.twig
  resources/views/applicant/application_index/index.html.twig
Labels: Bug, Low Complexity

#2727 Update NPM
  package-lock.json
  package.json
Labels: Dependency, NPM
