Repository GCTC-NTGC/TalentCloud, pull requests merged in 2020-02, with the labels that each got.

#2808 Update partner department list
  resources/lang/en/applicant/faq.php
  resources/lang/fr/applicant/faq.php
Labels: Copy

#2809 Fully refresh package-lock with changes related and unrelated to storybook addons 5.3.10
  package-lock.json
  package.json
Labels: Dependency, NPM

#2815 Fix translation migration columns
  app/Http/ViewComposers/FooterComposer.php
  database/migrations/2019_12_05_221612_add_translations_to_criteria_as_json.php
  database/migrations/2019_12_05_224054_add_translations_to_job_poster_questions_as_json.php
  database/migrations/2019_12_05_224501_add_translations_to_job_poster_key_tasks_as_json.php
  database/migrations/2019_12_06_002957_add_translations_to_team_culture_as_json.php
  database/migrations/2019_12_06_005552_add_translations_to_work_environment_as_json.php
  database/migrations/2019_12_06_010743_add_translations_to_managers_as_json.php
  database/migrations/2019_12_06_012307_add_translations_to_job_posters_as_json.php
Labels: Back-end, Low Complexity

#2852 Update Storybook and addons to 5.3.12
  package-lock.json
  package.json
Labels: Dependency, NPM

#2878 Improved logic for holiday message
  resources/views/applicant/home.html.twig
Labels: Priority, Refactor

#2586 Add Users API endpoint
  app/Exceptions/Handler.php
  app/Http/Controllers/Api/UserController.php
  app/Http/Resources/Applicant.php
  app/Http/Resources/Manager.php
  app/Http/Resources/User.php
  app/Models/User.php
  app/Policies/ApplicantPolicy.php
  app/Providers/AuthServiceProvider.php
  resources/assets/js/api/user.ts
  resources/assets/js/fakeData/fakeUsers.ts
  resources/assets/js/models/types.ts
  resources/assets/js/store/User/userActions.ts
  resources/assets/js/store/User/userReducer.test.ts
  resources/assets/js/store/User/userReducer.ts
  resources/assets/js/store/User/userSelector.ts
  resources/assets/js/store/store.ts
  routes/web.php
  tests/Feature/Api/UserControllerTest.php
Labels: Back-end, Front-end, Medium Complexity

#2908 Add User name and role to Activity Feed
  app/Http/Controllers/Admin/UserRoleCrudController.php
  app/Http/Requests/UserRoleCrudRequest.php
  app/Http/Resources/User.php
  app/Listeners/LogSuccessfulLogin.php
  app/Models/User.php
  app/Models/UserRole.php
  database/factories/UserFactory.php
  database/migrations/2020_02_11_154136_rename_name_to_key_on_user_roles_table.php
  database/migrations/2020_02_11_155505_add_name_to_user_roles_table.php
  resources/assets/js/components/ActivityList.tsx
  resources/assets/js/fakeData/fakeUsers.ts
  resources/assets/js/models/types.ts
  resources/assets/js/store/User/userSelector.ts
  resources/assets/js/store/store.ts
  resources/assets/js/stories/ActivityList.stories.tsx
  resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
  routes/backpack/custom.php
Labels: Front-end
